### ISSUE TITLE
Handling of missing fields?

### ISSUE THREAD

**Issue by siraben** [ChrisPenner/lens-csv#5]
In the example in the README, what happens if the CSV file has a missing entry, will it become the empty string? What about in the general case?

```haskell
>>> import Data.ByteString.Lazy as BL
>>> myCsv <- BL.readFile "./data/simple.csv"
>>> myCsv ^.. namedCsv . taking 2 rows . column @String "state_code" 
[ "NY"
, "CA"
]
```

**Comment by ChrisPenner** [comment]
This is handled mostly depending on which lens combinators you use, but also what you mean by "missing".

So, given the following (malformed) CSV, wherein `row1` has an empty second column, and `row2` actually *missing* the second column

```csv
first,second
row1,
row2
```

We get the following results:
```csv
>>> myCsv ^? namedCsv . row 0 . column @String "second"
Just ""
>>> myCsv ^? namedCsv . row 1 . column @String "second"
Nothing

>>> myCsv ^.. namedCsv . taking 2 rows . column @String "first"
["row1","row2"]
>>> myCsv ^.. namedCsv . taking 2 rows . column @String "second"
[""]

>>> myCsv ^. namedCsv . row 0 . column @String "second"
""
>>> myCsv ^. namedCsv . row 1 . column @String "second"
""
```

The latter is probably the least intuitive, but traversals can be used as Getters IF the value they return has a monoid instance, in which case it will return `mempty` if missing.

Hope that helps! I'll add some of this context to the readme.

**Comment by siraben** [comment]
I'm not too familiar with prisms, but would it be possible to return results of `Maybe Int` where reading empty/invalid fields result in `Maybe Int`? Then going over every row collecting the results into `[Maybe Int]`.

**Comment by ChrisPenner** [comment]
No worries, sure you can!

Given this csv:

```
name,age
John,37
Sylvia,banana
Sylvester,22
```

You can parse their ages like this:

```haskell
>>> myCsv ^.. namedCsv . rows . pre (column @Int "age")
[Just 37,Nothing,Just 22]
```

Notice that `column` will already try to parse things for you according to their `Read` instance (though you can parse things manually by just going through string first if you want)

[`pre`](https://hackage.haskell.org/package/lens-4.19.2/docs/Control-Lens-Combinators.html#v:pre) is a combinator that says "try the optic I give you, if it fails, return Nothing rather than omitting the result entirely"

There are a ton of combinators out there, so it can take a bit to get used to them, but it's a very flexible set of tools 😄

**Comment by ChrisPenner** [comment]
If you need a hand with anything feel free to drop by the [functional programming slack](https://fpchat-invite.herokuapp.com/) in the #haskell channel; Me and a lot of other Haskell folk hang out in there and are happy to answer questions 😄 

I also wrote a [book on optics](https://leanpub.com/optics-by-example) if you'd like to learn more about them in a structured sort of way

**Comment by siraben** [comment]
Thank you! I'll check it out.
